### ISSUE TITLE
clang-format version not specified

### ISSUE THREAD

**Issue by asergunov** [gchatelet/light_sequence_parser#8]
I was trying to use 3.3 and 3.6 but not all fields in .clang-format was recognized.

on ubuntu 14 3.6 is max you can get from the repo

Also it will be nice to have a script to format sources at once

**Comment by gchatelet** [comment]
Can you tell me which fields are not recognized ? I'm using archlinux and current version is 3.7.
Also please note I've [another branch](https://github.com/gchatelet/light_sequence_parser/tree/cleaner_version) where I'm simplifying testing, and restructuring the code a bit.

**Comment by asergunov** [comment]
YAML:16:39: error: invalid boolean
AlwaysBreakAfterDefinitionReturnType: None
                                      ^~~~
Error reading
/home/asergunov/amsanto/oo-cezanne/dependencies/light_sequence_parser/./.clang-format:
Invalid argument
-----
YAML:39:18: error: unknown key 'MacroBlockEnd'
MacroBlockEnd:   ''
                 ^~
Error reading
/home/asergunov/amsanto/oo-cezanne/dependencies/light_sequence_parser/.clang-format:
Invalid argument
Can't find usable .clang-format, using LLVM style
-----
YAML:6:30: error: unknown key 'AlignConsecutiveAssignments'
AlignConsecutiveAssignments: false
                             ^~~~~
Error reading
/home/asergunov/amsanto/oo-cezanne/dependencies/light_sequence_parser/.clang-format:
Invalid argument
Can't find usable .clang-format, using LLVM style

So removing these 3 lines make it work on 3.6 but result slightly different


вт, 24 нояб. 2015 г. в 12:55, Guillaume Chatelet <notifications@github.com>:

**Comment by asergunov** [comment]
I'm just trying to say - having clang version somewhere in docs is good a idea :)
